// Generated by @mawsoftwares/theme. Edit the design source, not this file.
import type { ThemeDefinition, ThemeOverrides } from '@mawsoftwares/theme';

export const theme: ThemeOverrides = {};

export const definition: ThemeDefinition = {
  id: 'default',
  overrides: theme,
};
