import { Router, type RequestHandler } from 'express';
import type { DrizzleDb } from '@mawsoftwares/database';
import { schema } from '@mawsoftwares/database';
import { eq, ilike, or, asc, desc, sql as sqlOp } from 'drizzle-orm';

// Customers: generated by scripts/generate-module.mjs — edit
// freely, this file is not regenerated once created.

function toCustomerDto(r: typeof schema.customers.$inferSelect) {
  return {
    id: r.id,
    name: r.name,
    email: r.email,
    mobile: r.mobile,
    companyName: r.companyName,
    status: r.status,
    createdAt: r.createdAt,
    updatedAt: r.updatedAt,
  };
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const SORT_COLUMNS: Record<string, any> = {
  createdAt: schema.customers.createdAt,
  updatedAt: schema.customers.updatedAt,
  name: schema.customers.name,
  email: schema.customers.email,
  mobile: schema.customers.mobile,
  companyName: schema.customers.companyName,
  status: schema.customers.status,
};

/**
 * Customers: generated CRUD module. Read access requires
 * `Read_Customers`; create/update/delete require `Create_Customers` /
 * `Update_Customers` / `Delete_Customers` respectively.
 */
export function createCustomersRouter(
  db: DrizzleDb,
  deps: {
    requireAuth: RequestHandler;
    requirePermission: (perm: string) => RequestHandler;
  },
): Router {
  const router = Router();
  const requireRead = deps.requirePermission('Read_Customers');
  const requireCreate = deps.requirePermission('Create_Customers');
  const requireUpdate = deps.requirePermission('Update_Customers');
  const requireDelete = deps.requirePermission('Delete_Customers');

  // List — search + sort + pagination.
  router.get('/', deps.requireAuth, requireRead, async (req, res) => {
    try {
      const page = Math.max(1, Number(req.query.page) || 1);
      const limit = Math.min(100, Math.max(1, Number(req.query.limit) || 20));
      const search = ((req.query.search as string) || '').trim();
      const sortKey = (req.query.sort as string) || 'createdAt';
      const orderFn = req.query.order === 'asc' ? asc : desc;
      const sortColumn = SORT_COLUMNS[sortKey] ?? schema.customers.createdAt;

      const where = search ? or(ilike(schema.customers.name, `%${search}%`), ilike(schema.customers.email, `%${search}%`), ilike(schema.customers.mobile, `%${search}%`), ilike(schema.customers.companyName, `%${search}%`)) : undefined;

      const [rows, totalRows] = await Promise.all([
        db.select().from(schema.customers).where(where).orderBy(orderFn(sortColumn)).limit(limit).offset((page - 1) * limit),
        db.select({ count: sqlOp<number>`count(*)::int` }).from(schema.customers).where(where),
      ]);
      const total = totalRows[0]?.count ?? 0;

      res.json({ data: { items: rows.map(toCustomerDto), total, page, limit } });
    } catch (err) {
      res.status(500).json({ error: (err as Error).message });
    }
  });

  router.get('/:id', deps.requireAuth, requireRead, async (req, res) => {
    try {
      const rows = await db.select().from(schema.customers).where(eq(schema.customers.id, String(req.params.id)));
      if (!rows[0]) return void res.status(404).json({ error: 'Customer not found' });
      res.json({ data: toCustomerDto(rows[0]) });
    } catch (err) {
      res.status(500).json({ error: (err as Error).message });
    }
  });

  router.post('/', deps.requireAuth, requireCreate, async (req, res) => {
    try {
      const body = req.body ?? {};
      if (!body.name || !body.email || !body.mobile) {
        return void res.status(400).json({ error: 'name, email, mobile are required' });
      }
      const rows = await db
        .insert(schema.customers)
        .values({
        name: body.name,
        email: body.email,
        mobile: body.mobile,
        companyName: body.companyName ?? null,
        status: body.status ?? null,
        })
        .returning();
      res.status(201).json({ data: toCustomerDto(rows[0]!) });
    } catch (err) {
      res.status(500).json({ error: (err as Error).message });
    }
  });

  router.put('/:id', deps.requireAuth, requireUpdate, async (req, res) => {
    try {
      const body = req.body ?? {};
      const rows = await db
        .update(schema.customers)
        .set({
        name: body.name,
        email: body.email,
        mobile: body.mobile,
        companyName: body.companyName,
        status: body.status,
          updatedAt: new Date(),
        })
        .where(eq(schema.customers.id, String(req.params.id)))
        .returning();
      if (!rows[0]) return void res.status(404).json({ error: 'Customer not found' });
      res.json({ data: toCustomerDto(rows[0]) });
    } catch (err) {
      res.status(500).json({ error: (err as Error).message });
    }
  });

  router.delete('/:id', deps.requireAuth, requireDelete, async (req, res) => {
    try {
      await db.delete(schema.customers).where(eq(schema.customers.id, String(req.params.id)));
      res.json({ success: true });
    } catch (err) {
      res.status(500).json({ error: (err as Error).message });
    }
  });

  return router;
}
