// Generated by `pnpm theme:generate`. Do not edit.
import { createThemeRegistry } from '@mawsoftwares/theme';
import { definition as defaultTheme } from './default/theme';
import { definition as evreghenTheme } from './evreghen/theme';

export const clientThemes = [defaultTheme, evreghenTheme];

export const themeRegistry = createThemeRegistry(clientThemes);
