-- Customer: generated by scripts/generate-module.mjs

CREATE TABLE IF NOT EXISTS customers (
  id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name                     VARCHAR(255) NOT NULL,
  email                    VARCHAR(255) NOT NULL,
  mobile                   VARCHAR(255) NOT NULL,
  company_name             VARCHAR(255),
  status                   VARCHAR(30) DEFAULT 'active',
  created_by               TEXT,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
