export enum FlagScope {
  GLOBAL = 'GLOBAL',
  ENVIRONMENT = 'ENVIRONMENT',
  PRODUCT = 'PRODUCT',
  TENANT = 'TENANT',
  USER = 'USER',
}

export enum FlagState {
  ON = 'ON',
  OFF = 'OFF',
  INHERIT = 'INHERIT',
}

export enum DependencyType {
  REQUIRES = 'REQUIRES',
  CONFLICTS_WITH = 'CONFLICTS_WITH',
}

export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum EvaluationReason {
  GLOBAL_DEFAULT = 'GLOBAL_DEFAULT',
  ENVIRONMENT_OVERRIDE = 'ENVIRONMENT_OVERRIDE',
  PRODUCT_OVERRIDE = 'PRODUCT_OVERRIDE',
  TENANT_OVERRIDE = 'TENANT_OVERRIDE',
  USER_OVERRIDE = 'USER_OVERRIDE',
  ROLLOUT = 'ROLLOUT',
  SCHEDULE_INACTIVE = 'SCHEDULE_INACTIVE',
  DEPENDENCY_DISABLED = 'DEPENDENCY_DISABLED',
  DEPENDENCY_CONFLICT = 'DEPENDENCY_CONFLICT',
  FLAG_DISABLED = 'FLAG_DISABLED',
  BILLING_DISABLED = 'BILLING_DISABLED',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  TARGETING_EXCLUDED = 'TARGETING_EXCLUDED',
  FALLBACK_SAFE_DEFAULT = 'FALLBACK_SAFE_DEFAULT',
}
