import { createTheme, googleFontUrl, tokensToCssVars, type ThemeOverrides } from '../index';
import { componentStateCss, DEFAULT_STATE_SPECS, type ComponentStateSpec } from '../components/states';
import { themeToCssText } from '../core/css';

export interface ExportCssOptions {
  /** Comment placed at the top of the file. */
  readonly header?: string;
  /** State specs for components beyond the built-in set. */
  readonly extraStateSpecs?: readonly ComponentStateSpec[];
}

/**
 * A complete stylesheet for a theme, usable without React: light and dark custom properties, responsive
 * overrides, the component state rules, and the font import when the font is one we can load.
 * The `maw-*` custom properties are the contract; components read them (see `ui-web`).
 */
export function exportThemeCss(overrides: ThemeOverrides, options: ExportCssOptions = {}): string {
  const theme = createTheme(overrides);
  const parts: string[] = [`/* ${options.header ?? 'Generated by @mawsoftwares/theme. Edit the design source, not this file.'} */`];

  const family = theme.typography.fontFamily;
  const fontUrl = googleFontUrl(overrides.typography?.fontFamily ?? overrides.branding?.fontFamily ?? family);
  if (fontUrl !== undefined) parts.push(`@import url('${fontUrl}');`);

  parts.push(themeToCssText(theme).trimEnd());

  // A state rule is emitted when either colour mode defines its token.
  const vars = { ...tokensToCssVars(false, theme), ...tokensToCssVars(true, theme) };
  const states = componentStateCss(vars, [...DEFAULT_STATE_SPECS, ...(options.extraStateSpecs ?? [])]);
  if (states !== '') parts.push(`/* Component states */\n${states}`);
  return `${parts.join('\n\n')}\n`;
}
