import type { ThemeOverrides } from '../index';
import { exportThemeCss } from './css';
import { exportThemeJson, type ExportJsonOptions } from './json';
import { exportThemeTs } from './ts';

export { exportThemeCss, type ExportCssOptions } from './css';
export {
  exportThemeJson, parseThemeJson, stripProvenance, ThemeFileError, THEME_FILE_FORMAT, THEME_FILE_VERSION,
  type ExportJsonOptions, type ThemeFile,
} from './json';
export { exportThemeTs, type ExportTsOptions } from './ts';
export { toTsLiteral, stableJson } from './literal';

export interface ThemeBundleOptions extends ExportJsonOptions {
  /** Registry id; also names the exported `definition` in `theme.ts`. */
  readonly id?: string;
}

export interface ThemeBundle {
  readonly 'theme.json': string;
  readonly 'theme.css': string;
  readonly 'theme.ts': string;
}

/** All three export formats of one theme. */
export function exportThemeBundle(overrides: ThemeOverrides, options: ThemeBundleOptions = {}): ThemeBundle {
  return {
    'theme.json': exportThemeJson(overrides, options),
    'theme.css': exportThemeCss(overrides, { header: `Theme${options.name === undefined ? '' : `: ${options.name}`}. Generated by @mawsoftwares/theme. Edit the design source, not this file.` }),
    'theme.ts': exportThemeTs(overrides, { ...(options.id === undefined ? {} : { id: options.id }), ...(options.extends === undefined ? {} : { extends: options.extends }) }),
  };
}
