import type { ThemeOverrides } from '../index';
import { stripProvenance } from './json';
import { toTsLiteral } from './literal';

export interface ExportTsOptions {
  /** Name of the exported `ThemeOverrides` constant. */
  readonly exportName?: string;
  /** When set, also exports a registry `definition` with this id. */
  readonly id?: string;
  readonly extends?: string;
  /** Default `false`: provenance lives in `theme.json`, and keeps this file short. */
  readonly includeProvenance?: boolean;
}

/** A TypeScript module exporting the theme as typed data, for apps that bundle their themes. */
export function exportThemeTs(overrides: ThemeOverrides, options: ExportTsOptions = {}): string {
  const name = options.exportName ?? 'theme';
  const data = options.includeProvenance === true ? overrides : stripProvenance(overrides);
  const hasDefinition = options.id !== undefined;
  const lines = [
    '// Generated by @mawsoftwares/theme. Edit the design source, not this file.',
    `import type { ${hasDefinition ? 'ThemeDefinition, ' : ''}ThemeOverrides } from '@mawsoftwares/theme';`,
    '',
    `export const ${name}: ThemeOverrides = ${toTsLiteral(data)};`,
  ];
  if (hasDefinition) {
    lines.push(
      '',
      'export const definition: ThemeDefinition = {',
      `  id: ${toTsLiteral(options.id)},`,
      ...(options.extends === undefined ? [] : [`  extends: ${toTsLiteral(options.extends)},`]),
      `  overrides: ${name},`,
      '};',
    );
  }
  return `${lines.join('\n')}\n`;
}
