version: '3.9'
services:
  api:
    container_name: {{appName}}
    build:
      context: {{deployPath}}
      dockerfile: Dockerfile
    ports:
      - "{{backendPort}}:{{backendPort}}"
    env_file:
      - .env
    restart: unless-stopped
