# {{envName}} — frontend dedicated-root HTTP
server {
  listen 80;
  server_name {{domain}};
  root {{staticRoot}};
  index index.html;
  client_max_body_size 50m;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
