import { pgTable, text, timestamp, uuid, varchar } from 'drizzle-orm/pg-core';

// Customer: generated by scripts/generate-module.mjs — edit freely,
// this file is not regenerated once created.
export const customers = pgTable('customers', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: varchar('name', { length: 255 }).notNull(),
  email: varchar('email', { length: 255 }).notNull(),
  mobile: varchar('mobile', { length: 255 }).notNull(),
  companyName: varchar('company_name', { length: 255 }),
  status: varchar('status', { length: 30 }).default("active"),
  createdBy: text('created_by'),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
});
