import type { ModuleDefinition } from '@mawsoftwares/rbac-core';

// Customers: generated by scripts/generate-module.mjs.
export const customersModule: ModuleDefinition = {
  key: 'customers',
  name: 'Customers',
  routePrefix: '/api/v1/customers',
  audience: 'admin',
  permissions: [
    { code: 'Read_Customers', name: 'Read Customers', description: 'View customers list and details' },
    { code: 'Create_Customers', name: 'Create Customers', description: 'Create new customers' },
    { code: 'Update_Customers', name: 'Update Customers', description: 'Edit existing customers' },
    { code: 'Delete_Customers', name: 'Delete Customers', description: 'Remove customers' },
  ],
  featureSync: {
    code: 'customers',
    name: 'Customers',
    groupCode: 'operations',
    routePath: '/customers',
    icon: 'list',
    sortOrder: 95,
    description: 'Manage customers',
  },
};
