import { createApi } from '@reduxjs/toolkit/query/react';
import { apiBaseQuery } from '../../store/apiBaseQuery';
import type { Customer, CreateCustomerInput, UpdateCustomerInput } from './types';

// Customers: generated by scripts/generate-module.mjs — the
// Redux Toolkit (RTK Query) data layer for this module, following the same
// pattern as features/users/usersApi.ts.
export interface ListCustomersResult {
  items: Customer[];
  total: number;
  page: number;
  limit: number;
}

export interface ListCustomersParams {
  page?: number;
  limit?: number;
  search?: string;
  sort?: string;
  order?: 'asc' | 'desc';
}

export const customersApi = createApi({
  reducerPath: 'customersApi',
  baseQuery: apiBaseQuery,
  tagTypes: ['Customer'],
  endpoints: (build) => ({
    listCustomers: build.query<ListCustomersResult, ListCustomersParams>({
      query: (params) => {
        const q = new URLSearchParams();
        if (params.page) q.set('page', String(params.page));
        if (params.limit) q.set('limit', String(params.limit));
        if (params.search) q.set('search', params.search);
        if (params.sort) q.set('sort', params.sort);
        if (params.order) q.set('order', params.order);
        return { url: `/api/v1/customers?${q.toString()}` };
      },
      transformResponse: (res: { data: ListCustomersResult }) => res.data,
      providesTags: (result) =>
        result
          ? [...result.items.map((item) => ({ type: 'Customer' as const, id: item.id })), { type: 'Customer' as const, id: 'LIST' }]
          : [{ type: 'Customer' as const, id: 'LIST' }],
    }),
    getCustomer: build.query<Customer, string>({
      query: (id) => ({ url: `/api/v1/customers/${id}` }),
      transformResponse: (res: { data: Customer }) => res.data,
      providesTags: (_result, _error, id) => [{ type: 'Customer', id }],
    }),
    createCustomer: build.mutation<Customer, CreateCustomerInput>({
      query: (body) => ({ url: '/api/v1/customers', method: 'POST', body }),
      transformResponse: (res: { data: Customer }) => res.data,
      invalidatesTags: [{ type: 'Customer', id: 'LIST' }],
    }),
    updateCustomer: build.mutation<Customer, { id: string; data: UpdateCustomerInput }>({
      query: ({ id, data }) => ({ url: `/api/v1/customers/${id}`, method: 'PUT', body: data }),
      transformResponse: (res: { data: Customer }) => res.data,
      invalidatesTags: (_result, _error, { id }) => [{ type: 'Customer', id }, { type: 'Customer', id: 'LIST' }],
    }),
    deleteCustomer: build.mutation<void, string>({
      query: (id) => ({ url: `/api/v1/customers/${id}`, method: 'DELETE' }),
      invalidatesTags: (_result, _error, id) => [{ type: 'Customer', id }, { type: 'Customer', id: 'LIST' }],
    }),
  }),
});

export const {
  useListCustomersQuery,
  useGetCustomerQuery,
  useCreateCustomerMutation,
  useUpdateCustomerMutation,
  useDeleteCustomerMutation,
} = customersApi;
