import { useState, useEffect, type ReactNode } from 'react';
import {
  Badge, Button, DataTable, DetailField, ErrorState, ListPage, Modal, PageLoader, Select, TextField, useForm, useToast,
  type ColumnDef, type SortState,
} from '@mawsoftwares/ui-web';
import {
  useListCustomersQuery,
  useCreateCustomerMutation,
  useUpdateCustomerMutation,
  useDeleteCustomerMutation,
} from './customersApi';
import type { Customer } from './types';

// Customers: generated by scripts/generate-module.mjs — edit
// freely, this file is not regenerated once created. Follows the same
// modal-based List/Create/Edit/Detail/Delete pattern already used by
// menus.tsx and messaging.tsx (this app has no nested/:id routes, so
// Add/Edit/View are modals off one List page rather than separate pages).

export function CustomersView(): ReactNode {
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(20);
  const [search, setSearch] = useState('');
  const [sort, setSort] = useState<SortState | undefined>(undefined);

  const { data, isLoading, isFetching, error, refetch } = useListCustomersQuery({
    page, limit: pageSize, search: search || undefined, sort: sort?.column, order: sort?.direction,
  });
  const [createMutation] = useCreateCustomerMutation();
  const [updateMutation] = useUpdateCustomerMutation();
  const [deleteMutation] = useDeleteCustomerMutation();
  const toast = useToast();

  const [showCreate, setShowCreate] = useState(false);
  const [editing, setEditing] = useState<Customer | null>(null);
  const [viewing, setViewing] = useState<Customer | null>(null);

  const form = useForm({
    initialValues: { name: '', email: '', mobile: '', companyName: '', status: "active" },
    fields: { name: { required: true }, email: { required: true }, mobile: { required: true } },
    onSubmit: async (values) => {
      try {
        await createMutation(values as any).unwrap();
        toast.success('Customer created');
        setShowCreate(false);
        form.reset();
      } catch (e) {
        toast.error((e as Error).message);
      }
    },
  });

  const editForm = useForm({
    initialValues: { name: '', email: '', mobile: '', companyName: '', status: "active" },
    fields: { name: { required: true }, email: { required: true }, mobile: { required: true } },
    onSubmit: async (values) => {
      if (!editing) return;
      try {
        await updateMutation({ id: editing.id, data: values as any }).unwrap();
        toast.success('Customer updated');
        setEditing(null);
      } catch (e) {
        toast.error((e as Error).message);
      }
    },
  });

  useEffect(() => {
    if (editing) {
      editForm.reset({ name: editing.name, email: editing.email, mobile: editing.mobile, companyName: editing.companyName, status: editing.status });
    }
  }, [editing]);

  const remove = async (id: string) => {
    if (!window.confirm('Delete this customer?')) return;
    try {
      await deleteMutation(id).unwrap();
      toast.success('Customer deleted');
    } catch (e) {
      toast.error((e as Error).message);
    }
  };

  if (error) return <ErrorState title="Failed to load customers" message="Something went wrong" retry={refetch} />;
  if (isLoading) return <PageLoader message="Loading customers..." />;

  const items = data?.items ?? [];
  const total = data?.total ?? 0;

  const columns: ColumnDef<Customer>[] = [
  { key: 'name', header: 'Name', sortable: true },
  { key: 'email', header: 'Email', sortable: true },
  { key: 'mobile', header: 'Mobile', sortable: true },
  { key: 'companyName', header: 'Company Name', sortable: true },
  { key: 'status', header: 'Status', render: (row) => <Badge variant={row.status === 'active' ? 'success' : 'danger'}>{row.status}</Badge> },
    {
      key: 'actions' as any,
      header: 'Actions',
      render: (row) => (
        <div style={{ display: 'flex', gap: 8 }}>
          <Button variant="ghost" onClick={() => setViewing(row)}>View</Button>
          <Button variant="ghost" onClick={() => setEditing(row)}>Edit</Button>
          <Button variant="ghost" onClick={() => remove(row.id)} style={{ color: 'var(--maw-danger)' }}>Delete</Button>
        </div>
      ),
    },
  ];

  return (
    <ListPage
      title="Customers"
      description={total + ' customers'}
      createLabel="Create Customer"
      onCreate={() => setShowCreate(true)}
      filter={search}
      onFilterChange={(v) => { setSearch(v); setPage(1); }}
    >
      <DataTable
        columns={columns}
        data={items}
        keyField="id"
        sort={sort}
        onSort={setSort}
        pagination={{ page, pageSize, total }}
        onPageChange={setPage}
        onPageSizeChange={setPageSize}
        loading={isFetching}
        emptyMessage="No customers found"
      />

      <Modal open={showCreate} onClose={() => setShowCreate(false)} title="Create Customer">
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16, marginTop: 16 }}>
      <TextField label="Name" required error={form.errors.name} value={form.values.name}
        onChange={(e) => form.setValue('name', (e.target as HTMLInputElement).value)} />
      <TextField label="Email" required error={form.errors.email} value={form.values.email}
        onChange={(e) => form.setValue('email', (e.target as HTMLInputElement).value)} />
      <TextField label="Mobile" required error={form.errors.mobile} value={form.values.mobile}
        onChange={(e) => form.setValue('mobile', (e.target as HTMLInputElement).value)} />
      <TextField label="Company Name" value={form.values.companyName}
        onChange={(e) => form.setValue('companyName', (e.target as HTMLInputElement).value)} />
      <Select label="Status" value={form.values.status} options={[{ value: "active", label: "Active" }, { value: "inactive", label: "Inactive" }]}
        onChange={(e) => form.setValue('status', (e.target as HTMLSelectElement).value)} />
          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8, marginTop: 8 }}>
            <Button variant="ghost" onClick={() => setShowCreate(false)}>Cancel</Button>
            <Button onClick={() => form.handleSubmit()} disabled={form.submitting}>Create</Button>
          </div>
        </div>
      </Modal>

      <Modal open={!!editing} onClose={() => setEditing(null)} title={'Edit Customer'}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16, marginTop: 16 }}>
      <TextField label="Name" required error={editForm.errors.name} value={editForm.values.name}
        onChange={(e) => editForm.setValue('name', (e.target as HTMLInputElement).value)} />
      <TextField label="Email" required error={editForm.errors.email} value={editForm.values.email}
        onChange={(e) => editForm.setValue('email', (e.target as HTMLInputElement).value)} />
      <TextField label="Mobile" required error={editForm.errors.mobile} value={editForm.values.mobile}
        onChange={(e) => editForm.setValue('mobile', (e.target as HTMLInputElement).value)} />
      <TextField label="Company Name" value={editForm.values.companyName}
        onChange={(e) => editForm.setValue('companyName', (e.target as HTMLInputElement).value)} />
      <Select label="Status" value={editForm.values.status} options={[{ value: "active", label: "Active" }, { value: "inactive", label: "Inactive" }]}
        onChange={(e) => editForm.setValue('status', (e.target as HTMLSelectElement).value)} />
          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8, marginTop: 8 }}>
            <Button variant="ghost" onClick={() => setEditing(null)}>Cancel</Button>
            <Button onClick={() => editForm.handleSubmit()} disabled={editForm.submitting}>Save Changes</Button>
          </div>
        </div>
      </Modal>

      <Modal open={!!viewing} onClose={() => setViewing(null)} title="Customer Details">
        {viewing && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12, marginTop: 16 }}>
        <DetailField label="Name" value={viewing.name ?? '\u2014'} />
        <DetailField label="Email" value={viewing.email ?? '\u2014'} />
        <DetailField label="Mobile" value={viewing.mobile ?? '\u2014'} />
        <DetailField label="Company Name" value={viewing.companyName ?? '\u2014'} />
        <DetailField label="Status" value={viewing.status ?? '\u2014'} />
          </div>
        )}
      </Modal>
    </ListPage>
  );
}
