// Customer: generated by scripts/generate-module.mjs.
export interface Customer {
  id: string;
  name: string;
  email: string;
  mobile: string;
  companyName?: string;
  status?: "active" | "inactive";
  createdAt: string;
  updatedAt: string;
}

export type CreateCustomerInput = Omit<Customer, 'id' | 'createdAt' | 'updatedAt'>;
export type UpdateCustomerInput = Partial<CreateCustomerInput>;
